name: AKS Deployment

on:
  workflow_run:
    workflows: ["Docker"]
    types:
      - completed

jobs:
  deploy-aks:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y azure-cli

      
      - name: Set up Azure CLI with Managed Identity
        run: |
          az login --identity

      - name: Configure kubectl
        run: az aks get-credentials --resource-group semester6 --name schoolcluster

      - name: Deploy to AKS
        run: kubectl apply -f taskboarding-frontend-deployment.yaml

