name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install k3d
      run: |
        wget -q -O k3d https://github.com/rancher/k3d/releases/download/v4.4.5/k3d-linux-amd64
        chmod +x k3d
        sudo mv k3d /usr/local/bin/

    - name: Create k3d Cluster
      run: k3d cluster create semester6 --servers 1 --agents 1 --port 9080:80@loadbalancer

    - name: Set kubectl context to k3d-semester6
      run: kubectl config use-context k3d-semester6

    - name: Delete existing Deployment
      run: kubectl delete deployment taskboarding-frontend --context=k3d-semester6 || true

    - name: Apply Kubernetes manifests
      run: kubectl apply -f taskboarding-frontend-deployment.yaml --context=k3d-semester6

    - name: Check Deployment Events
      run: kubectl get events --context=k3d-semester6


    - name: Wait for deployment to finish
      run: kubectl rollout status deployment/taskboarding-frontend --context=k3d-semester6

    - name: Clean up k3d cluster
      run: k3d cluster delete semester6

